### ISSUE TITLE
Error Encountered While Running the Program

### ISSUE THREAD

**Issue by zerosurplus** [SMARTlab-Purdue/SMART-LLM#4]
(smartllm) D:\project\SMART-LLM-master>python scripts/run_llm.py --floor-plan 6

----Test set tasks----
['Slice the tomato', 'Wash the lettuce and place lettuce on the Countertop', 'Throw the Spatula in the trash']
Total: 3 tasks

Traceback (most recent call last):
  File "D:\project\SMART-LLM-master\scripts\run_llm.py", line 122, in <module>
    objects_ai = f"\n\nobjects = {get_ai2_thor_objects(args.floor_plan)}"
  File "D:\project\SMART-LLM-master\scripts\run_llm.py", line 57, in get_ai2_thor_objects
    controller = ai2thor.controller.Controller(scene="FloorPlan"+str(floor_plan_id))
  File "D:\anaconda3\envs\smartllm\lib\site-packages\ai2thor\controller.py", line 513, in __init__        
    self._build = self.find_build(local_build, commit_id, branch, platform)
  File "D:\anaconda3\envs\smartllm\lib\site-packages\ai2thor\controller.py", line 1306, in find_build     
    raise ValueError(
ValueError: Invalid commit_id: f0825767cd50d69f666c7f282e54abfe58f1e917 - no build exists for arch=Windows platforms=

(smartllm) D:\project\SMART-LLM-master>python scripts/run_llm.py --floor-plan 15
Traceback (most recent call last):
  File "D:\project\SMART-LLM-master\scripts\run_llm.py", line 97, in <module>
    test_tasks.append(list(json.loads(line).values())[0])
  File "D:\anaconda3\envs\smartllm\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda3\envs\smartllm\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda3\envs\smartllm\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 152 (char 151)
I am experiencing an error when I try to execute the program, and I would appreciate any help you could provide to resolve this issue.

**Comment by h-zhichao-w** [comment]
Same issue. With the same commit id. Not solved yet.

**Comment by lowerbound123** [comment]
I found that convert "None" to some other elements which are supported by json can solve this problem. Such as "" -- empty syring.

**Comment by XiaozhuLove** [comment]
(p_web) PS D:\graduate\deeplearning\1_new_work\LLM\agentcode\SMART-LLM-master> python scripts/run_llm.py --floor-plan 6

----Test set tasks----
['Slice the tomato', 'Wash the lettuce and place lettuce on the Countertop', 'Throw the Spatula in the trash']
Total: 3 tasks

Traceback (most recent call last):
  File "D:\graduate\deeplearning\1_new_work\LLM\agentcode\SMART-LLM-master\scripts\run_llm.py", line 122, in <module>
    objects_ai = f"\n\nobjects = {get_ai2_thor_objects(args.floor_plan)}"
  File "D:\graduate\deeplearning\1_new_work\LLM\agentcode\SMART-LLM-master\scripts\run_llm.py", line 57, in get_ai2_thor_objects
    controller = ai2thor.controller.Controller(scene="FloorPlan"+str(floor_plan_id))
  File "C:\Users\87400\anaconda3\envs\p_web\lib\site-packages\ai2thor\controller.py", line 513, in __init__
    self._build = self.find_build(local_build, commit_id, branch, platform)
  File "C:\Users\87400\anaconda3\envs\p_web\lib\site-packages\ai2thor\controller.py", line 1306, in find_build
    raise ValueError(
ValueError: Invalid commit_id: f0825767cd50d69f666c7f282e54abfe58f1e917 - no build exists for arch=Windows platforms=

I am experiencing the error, Why is that? I would appreciate any help you could provide to resolve this issue.

**Comment by lowerbound123** [comment]
> (p_web) PS D:\graduate\deeplearning\1_new_work\LLM\agentcode\SMART-LLM-master> python scripts/run_llm.py --floor-plan 6
> 
> ----Test set tasks---- ['Slice the tomato', 'Wash the lettuce and place lettuce on the Countertop', 'Throw the Spatula in the trash'] Total: 3 tasks
> 
> Traceback (most recent call last): File "D:\graduate\deeplearning\1_new_work\LLM\agentcode\SMART-LLM-master\scripts\run_llm.py", line 122, in objects_ai = f"\n\nobjects = {get_ai2_thor_objects(args.floor_plan)}" File "D:\graduate\deeplearning\1_new_work\LLM\agentcode\SMART-LLM-master\scripts\run_llm.py", line 57, in get_ai2_thor_objects controller = ai2thor.controller.Controller(scene="FloorPlan"+str(floor_plan_id)) File "C:\Users\87400\anaconda3\envs\p_web\lib\site-packages\ai2thor\controller.py", line 513, in **init** self._build = self.find_build(local_build, commit_id, branch, platform) File "C:\Users\87400\anaconda3\envs\p_web\lib\site-packages\ai2thor\controller.py", line 1306, in find_build raise ValueError( ValueError: Invalid commit_id: f0825767cd50d69f666c7f282e54abfe58f1e917 - no build exists for arch=Windows platforms=
> 
> I am experiencing the error, Why is that? I would appreciate any help you could provide to resolve this issue.

It looks like a problem with ai2thor, do you have the correct installation of it? Maybe you can visit ai2thor's website to search how to check its installation.
I have not been use windows for a long time. Maybe you can use ubuntu to run this code. On Windows, maybe wsl is possible too.
